import assert from 'node:assert/strict'
import { it } from 'node:test'

import { CURRENT_ATTESTOR_VERSION, PROVIDER_CTX } from '#src/config/index.ts'
import httpProvider from '#src/providers/http/index.ts'
import type { ProviderParams, Transcript } from '#src/types/index.ts'
import { logger, redactSlices } from '#src/utils/index.ts'

const name = 'Привет'
const wrongName = new TextDecoder('windows-1251').decode(Buffer.from(name))
function response(body: Uint8Array) {
	return Buffer.concat([Buffer.from(`HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: ${body.length}\r\n\r\n`), body])
}
function verify(bytes: Uint8Array, value: string) {
	const receipt: Transcript<Uint8Array> = [
		{ sender: 'client', message: Buffer.from('GET / HTTP/1.1\r\nHost: example.com\r\nConnection: close\r\n\r\n') },
		{ sender: 'server', message: bytes },
	]
	const params: ProviderParams<'http'> = { url: 'https://example.com/', method: 'GET', responseMatches: [{ type: 'contains', value }] }
	return httpProvider.assertValidProviderReceipt({ receipt, params, logger, ctx: PROVIDER_CTX, clientVersion: CURRENT_ATTESTOR_VERSION })
}

it('does not let a hidden UTF-8 BOM select a different document charset', async() => {
	const body = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(`<meta charset=windows-1251><p>${name}</p>`)])
	await verify(response(body), name)
	body.fill(42, 0, 3)
	await assert.rejects(async() => verify(response(body), wrongName))
})

it('does not promote a commented declaration when comment delimiters are hidden', async() => {
	const body = Buffer.from(`<!--<meta charset=windows-1251>--><p>${name}</p>`)
	await verify(response(body), name)
	body.fill(42, 0, 4)
	const close = body.indexOf('-->')
	body.fill(42, close, close + 3)
	await assert.rejects(async() => verify(response(body), wrongName))
})

it('accepts script JSON receipts generated by the TypeScript redactor', async() => {
	const raw = response(Buffer.from(`<script>{"fake":"<meta charset=windows-1251>","name":"${name}"}</script>`))
	const params: ProviderParams<'http'> = {
		url: 'https://example.com/', method: 'GET', responseMatches: [{ type: 'contains', value: name }], responseRedactions: [{ xPath: '//script/text()' }],
	}
	const ranges = httpProvider.getResponseRedactions!({ response: raw, params, logger, ctx: PROVIDER_CTX })
	await verify(redactSlices(raw, ranges), name)
})
