import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { it } from 'node:test'

import { CURRENT_ATTESTOR_VERSION, PROVIDER_CTX } from '#src/config/index.ts'
import { AttestorVersion } from '#src/proto/api.ts'
import { KOutputPayload, SignedMessage, TOutputPayload } from '#src/proto/tee-bundle.ts'
import httpProvider from '#src/providers/http/index.ts'
import { charsetFromAuthenticatedPrefix, reconstructTlsTranscript } from '#src/server/utils/tee-transcript-reconstruction.ts'
import type { ProviderParams, Transcript } from '#src/types/index.ts'
import { logger, redactSlices } from '#src/utils/index.ts'

const name = 'Привет'
const wrongName = new TextDecoder('windows-1251').decode(Buffer.from(name))
function response(body: Uint8Array) {
	return Buffer.concat([Buffer.from(`HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: ${body.length}\r\n\r\n`), body])
}
function verify(bytes: Uint8Array, value: string, redactions?: { start: number, length: number }[], replacements?: { position: number, length: number }[], verifiedCharset?: string) {
	const receipt: Transcript<Uint8Array> = [
		{ sender: 'client', message: Buffer.from('GET / HTTP/1.1\r\nHost: example.com\r\nConnection: close\r\n\r\n') },
		{ sender: 'server', message: bytes },
	]
	const params: ProviderParams<'http'> = { url: 'https://example.com/', method: 'GET', responseMatches: [{ type: 'contains', value }] }
	return httpProvider.assertValidProviderReceipt({ receipt, params, logger, ctx: { ...PROVIDER_CTX, authenticatedResponseCharset: verifiedCharset ?? (redactions ? charsetFromAuthenticatedPrefix(bytes, redactions, replacements) : undefined) }, clientVersion: CURRENT_ATTESTOR_VERSION })
}

it('does not let a hidden UTF-8 BOM select a different document charset', async() => {
	const body = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(`<meta charset=windows-1251><p>${name}</p>`)])
	await verify(response(body), name)
	body.fill(42, 0, 3)
	await assert.rejects(async() => verify(response(body), wrongName, [{ start: response(body).length - body.length, length: 3 }]))
})

it('does not promote a commented declaration when comment delimiters are hidden', async() => {
	const body = Buffer.from(`<!--<meta charset=windows-1251>--><p>${name}</p>`)
	await verify(response(body), name)
	body.fill(42, 0, 4)
	const close = body.indexOf('-->')
	body.fill(42, close, close + 3)
	await assert.rejects(async() => verify(response(body), wrongName, [{ start: response(body).length - body.length, length: 4 }, { start: response(body).length - body.length + close, length: 3 }]))
})

it('accepts script JSON receipts generated by the TypeScript redactor', async() => {
	const raw = response(Buffer.from(`<script>{"fake":"<meta charset=windows-1251>","name":"${name}"}</script>`))
	const params: ProviderParams<'http'> = {
		url: 'https://example.com/', method: 'GET', responseMatches: [{ type: 'contains', value: name }], responseRedactions: [{ xPath: '//script/text()' }],
	}
	const ranges = httpProvider.getResponseRedactions!({ response: raw, params, logger, ctx: PROVIDER_CTX })
	await verify(redactSlices(raw, ranges), name)
})


it('uses an authenticated public declaration before a private suffix', async() => {
	const body = Buffer.concat([Buffer.from('<meta charset=windows-1251><p>'), Buffer.from([0xcf, 0xf0, 0xe8, 0xe2, 0xe5, 0xf2]), Buffer.from('</p>PRIVATE')])
	const bytes = response(body)
	const start = bytes.length - 7
	bytes.fill(42, start)
	const ranges = [{ start, length: 7 }]
	assert.equal(charsetFromAuthenticatedPrefix(bytes, ranges), 'windows-1251')
	await verify(bytes, name, ranges)
})

it('does not trust a hash-replaced prefix even without asterisks', () => {
	const bytes = response(Buffer.from('hashvalue<meta charset=windows-1251>'))
	const start = bytes.indexOf('hashvalue')
	assert.equal(charsetFromAuthenticatedPrefix(bytes, [], [{ position: start, length: 9 }]), undefined)
})

it('requires complete public headers before trusting document declarations', () => {
	const bytes = response(Buffer.from('<meta charset=windows-1251>'))
	assert.equal(charsetFromAuthenticatedPrefix(bytes, [{ start: 18, length: 1 }]), undefined)
})

it('does not use XML fallback while a later meta may be hidden', () => {
	const bytes = response(Buffer.from('<?xml encoding="windows-1251"?><meta charset=windows-1252>'))
	assert.equal(charsetFromAuthenticatedPrefix(bytes, [{ start: bytes.indexOf('<meta'), length: 1 }]), undefined)
})

it('allows literal asterisks in authenticated public bytes', () => {
	const bytes = response(Buffer.from('<!--***--><meta charset=windows-1251>PRIVATE'))
	assert.equal(charsetFromAuthenticatedPrefix(bytes, [{ start: bytes.length - 7, length: 7 }]), 'windows-1251')
})

it('maps a public prefix across chunk framing', async() => {
	const first = Buffer.from('<meta charset=windows-1251>')
	const second = Buffer.concat([Buffer.from('<p>'), Buffer.from([0xcf, 0xf0, 0xe8, 0xe2, 0xe5, 0xf2]), Buffer.from('</p>PRIVATE')])
	const bytes = Buffer.concat([Buffer.from('HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nTransfer-Encoding: chunked\r\n\r\n'), Buffer.from(first.length.toString(16) + '\r\n'), first, Buffer.from('\r\n' + second.length.toString(16) + '\r\n'), second, Buffer.from('\r\n0\r\n\r\n')])
	const start = bytes.indexOf('PRIVATE')
	const ranges = [{ start, length: 7 }]
	bytes.fill(42, start, start + 7)
	assert.equal(charsetFromAuthenticatedPrefix(bytes, ranges), 'windows-1251')
	await verify(bytes, name, ranges)
})


it('derives TEE charset before reconstruction transformations using signed ranges', async() => {
	const bytes = response(Buffer.from('<meta charset=windows-1251>PRIVATE'))
	const start = bytes.length - 7
	const kOutputPayload = KOutputPayload.create({ redactedRequest: Buffer.from('GET / HTTP/1.1\r\n\r\n'), consolidatedResponseKeystream: new Uint8Array(bytes.length), responseRedactionRanges: [{ start, length: 7 }] })
	const bundle = { teekSigned: SignedMessage.create({}), teetSigned: SignedMessage.create({}), kOutputPayload, tOutputPayload: TOutputPayload.create({ consolidatedResponseCiphertext: bytes }), teekPcr0: 'test-k', teetPcr0: 'test-t', teeSessionId: 'test', protocolMode: 'split-aead' as const }
	const publicPrefix = await reconstructTlsTranscript(bundle, logger)
	assert.equal(publicPrefix.authenticatedResponseCharset, 'windows-1251')
	assert.equal(Buffer.from(publicPrefix.reconstructedResponse).includes('PRIVATE'), false)
	kOutputPayload.responseRedactionRanges.push({ start: bytes.indexOf('<meta'), length: 1 })
	const hiddenPrefix = await reconstructTlsTranscript(bundle, logger)
	assert.equal(hiddenPrefix.authenticatedResponseCharset, undefined)
})


for(const transferHeader of ['Transfer-Encoding: chunked', 'Transfer-Encoding: Chunked', 'Transfer-Encoding:chunked', 'tRaNsFeR-EnCoDiNg:\tChUnKeD']) {
	for(const mode of ['split-aead', 'tls12-cbc'] as const) {
		it(`preserves BOM precedence through ${transferHeader} (${mode})`, async() => {
			const body = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from(`<meta charset=windows-1251><p>${name}</p>`)])
			// Split inside the BOM to exercise raw-to-dechunked coordinates.
			const parts = [body.subarray(0, 1), body.subarray(1, 2), body.subarray(2)]
			const bytes = Buffer.concat([Buffer.from(`HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n${transferHeader}\r\n\r\n`), ...parts.flatMap(part => [Buffer.from(part.length.toString(16) + '\r\n'), part, Buffer.from('\r\n')]), Buffer.from('0\r\n\r\n')])
			const kOutputPayload = KOutputPayload.create({ redactedRequest: Buffer.from('GET / HTTP/1.1\r\n\r\n'), consolidatedResponseKeystream: new Uint8Array(bytes.length), tls12Cbc: mode === 'tls12-cbc' ? { authenticatedRedactedRequest: Buffer.from('GET / HTTP/1.1\r\n\r\n') } : undefined })
			const tOutputPayload = TOutputPayload.create({ consolidatedResponseCiphertext: bytes, tls12Cbc: mode === 'tls12-cbc' ? { authenticatedRedactedResponse: bytes } : undefined })
			const bundle = { teekSigned: SignedMessage.create({}), teetSigned: SignedMessage.create({}), kOutputPayload, tOutputPayload, teekPcr0: 'test-k', teetPcr0: 'test-t', teeSessionId: 'test', protocolMode: mode }
			const reconstructed = await reconstructTlsTranscript(bundle, logger)
			assert.equal(reconstructed.authenticatedResponseCharset, 'utf-8')
			await verify(reconstructed.reconstructedResponse, name, undefined, undefined, reconstructed.authenticatedResponseCharset)
			await assert.rejects(async() => verify(reconstructed.reconstructedResponse, wrongName, undefined, undefined, reconstructed.authenticatedResponseCharset))
			const bodyStart = bytes.indexOf('\r\n\r\n') + 4
			const firstDataByte = bodyStart + 3
			assert.equal(charsetFromAuthenticatedPrefix(bytes, [{ start: firstDataByte, length: 1 }]), undefined)
		})
	}
}


// Generated with reclaim-tee GetResponseRedactions at 4dc36db, using
// <html><head><meta charset=windows-1251></head><body><span>Привет</span></body></html>
// and XPath //span/text(). These are known coverage limits, not successful claims.
const goReceipts: { cbc: boolean, response: string, redactions: { start: number, length: number }[], match: string }[] = JSON.parse(readFileSync(new URL('./fixtures/go-charset-prefix-limits.json', import.meta.url), 'utf8'))
for(const fixture of goReceipts) {
	it(`documents actual Go receipt prefix limits (cbc=${fixture.cbc})`, async() => {
		const bytes = Buffer.from(fixture.response, 'base64')
		assert.equal(charsetFromAuthenticatedPrefix(bytes, fixture.redactions), undefined)
		await assert.rejects(async() => verify(bytes, fixture.match, fixture.redactions))
	})
}


it('does not treat parser-truncated hidden chunks as a fully public body', () => {
	const xml = Buffer.from('<?xml encoding="windows-1251"?>')
	const bytes = Buffer.concat([Buffer.from('HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nTransfer-Encoding: Chunked\r\n\r\n'), Buffer.from(xml.length.toString(16) + '\r\n'), xml, Buffer.from('\r\n********************\r\n0\r\n\r\n')])
	const start = bytes.indexOf('********************')
	assert.equal(charsetFromAuthenticatedPrefix(bytes, [{ start, length: 20 }]), undefined)
})


for(const header of [
	'X-Test: transfer-encoding: chunked',
	'Transfer-Encoding: chunkedgarbage',
	'Transfer-Encoding: gzip, chunked',
	'Transfer-Encoding: chunked\r\nContent-Length: 0',
	'Transfer-Encoding: chunked\r\nTransfer-Encoding: identity',
	'Transfer-Encoding: chunked\r\nContent-Encoding: gzip',
]) {
	it(`does not authorize a charset under ambiguous framing: ${header}`, () => {
		const body = Buffer.from('<meta charset=windows-1251>')
		const bytes = Buffer.concat([Buffer.from(`HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n${header}\r\n\r\n${body.length.toString(16)}\r\n`), body, Buffer.from('\r\n0\r\n\r\n')])
		assert.equal(charsetFromAuthenticatedPrefix(bytes, []), undefined)
	})
}

it('does not authorize a charset from unequal AEAD shares', async() => {
	const prefix = Buffer.from('HTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\n<?xml encoding="windows-1251"?><p>public</p>')
	const bytes = Buffer.concat([prefix, Buffer.from('<meta charset=utf-8>')])
	const bundle = { teekSigned: SignedMessage.create({}), teetSigned: SignedMessage.create({}), kOutputPayload: KOutputPayload.create({ redactedRequest: Buffer.from('GET / HTTP/1.1\r\n\r\n'), consolidatedResponseKeystream: new Uint8Array(prefix.length) }), tOutputPayload: TOutputPayload.create({ consolidatedResponseCiphertext: bytes }), teekPcr0: 'test-k', teetPcr0: 'test-t', teeSessionId: 'test', protocolMode: 'split-aead' as const }
	const result = await reconstructTlsTranscript(bundle, logger)
	assert.equal(result.authenticatedResponseCharset, undefined)
})

for(const label of ['&#160;windows-1251&#160;', '&nbsp;windows-1251&nbsp;', '\vwindows-1251\v', '&nbsp;x-user-defined&nbsp;']) {
	it(`does not accept non-ASCII label whitespace: ${label}`, () => {
		assert.equal(charsetFromAuthenticatedPrefix(response(Buffer.from(`<meta charset="${label}"><p>${name}</p>`)), []), 'utf-8')
	})
}


it('does not apply a document charset to legacy status-relative body offsets', async() => {
	const bytes = response(Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from('<p>Привет</p>', 'utf16le')]))
	const charset = charsetFromAuthenticatedPrefix(bytes, [])
	assert.equal(charset, 'utf-16le')
	const wrongText = new TextDecoder(charset).decode(bytes.subarray('HTTP/1.1 200'.length))
	const receipt: Transcript<Uint8Array> = [{ sender: 'client', message: Buffer.from('GET / HTTP/1.1\r\nHost: example.com\r\nConnection: close\r\n\r\n') }, { sender: 'server', message: bytes }]
	for(const version of [AttestorVersion.ATTESTOR_VERSION_1_0_0, AttestorVersion.ATTESTOR_VERSION_2_0_0]) {
		const params: ProviderParams<'http'> = { url: 'https://example.com/', method: 'GET', responseMatches: [{ type: 'contains', value: wrongText }] }
		await assert.rejects(async() => httpProvider.assertValidProviderReceipt({ receipt, params, logger, ctx: { version, authenticatedResponseCharset: charset }, clientVersion: version }))
	}
})
