extends: '@adiwajshing'
parserOptions:
  project: ./tsconfig.json
  sourceType: "module"
plugins:
  - no-relative-import-paths
rules:
  '@typescript-eslint/no-explicit-any': 0
  'no-relative-import-paths/no-relative-import-paths':
    - error
    - allowSameFolder: false
      rootDir: ''
  '@typescript-eslint/no-floating-promises':
    - error

      