name: Build & Publish Docker Image (Staging)

on:
  workflow_run:
    workflows: ["Test (Staging)"]
    branches:
      - staging
    types:
      - completed

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      packages: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: reclaimprotocol
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build & Push Image
        uses: docker/build-push-action@v5
        with:
          build-args: GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max`
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/reclaimprotocol/${{ github.event.repository.name }}:staging-${{ github.sha }}
          file: attestor.dockerfile
