name: Deploy
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Deploy Stage
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'reclaimprotocol',
              repo: 'attestor-deployment',
              workflow_id: 'update-deployment.yaml',
              ref: 'main',
            });