name: Publish to NPM

permissions:
  contents: write
  id-token: write  # Required for OIDC

# Manually triggered workflow
on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
